#include <QtTest>
#include <QJsonArray>
#include "CrystalReport.h"
#include "StoragePolicy.h"
class CrystalTests:public QObject {
 Q_OBJECT
 QString report()const{return QStringLiteral("CrystalDiskInfo 9.9.2\n (01) SYNTHETIC ATA FIXTURE\n----------------------------\n Model : SYNTHETIC ATA FIXTURE\n Firmware : TEST\n Serial Number : TEST-C5-16\n Interface : Serial ATA\n Health Status : Good\n Temperature : 33 C (91 F)\n Power On Hours : 11862 hours\n Power On Count : 3124 count\n ID Cur Wor Thr RawValues(6) Attribute Name\n05 100 100 _10 000000000000 Reallocated Sectors Count\nC5 100 100 __0 000000000010 Current Pending Sector Count\nC6 100 100 __0 000000000000 Uncorrectable Sector Count\nC2 _33 _13 __0 000000000021 Temperature\n");}
private slots:
 void pendingSixteenOverridesGood(){auto r=dc::parseCrystalReport(report());QCOMPARE(r.value("status").toString(),"completed");auto disks=r.value("drives").toArray();QCOMPARE(disks.size(),1);auto s=disks[0].toObject().value("summary").toObject();QCOMPARE(s.value("health").toString(),"caution");QCOMPARE(s.value("pending").toInt(),16);QCOMPARE(s.value("temperature").toInt(),33);QCOMPARE(s.value("hours").toInt(),11862);QVERIFY(s.value("rescueFirst").toBool());QCOMPARE(s.value("attributes").toArray().size(),4);}
 void nvmePercentageIsNotReallocation(){auto text=report()+QStringLiteral(" (02) SYNTHETIC NVME\n----------------------------\n Model : SYNTHETIC NVME\n Serial Number : TEST-NVME\n Interface : NVM Express\n Health Status : Good (90 %)\n01 000000000000 Critical Warning\n05 00000000000A Percentage Used\n0E 000000000000 Media and Data Integrity Errors\n");auto disks=dc::parseCrystalReport(text).value("drives").toArray();QCOMPARE(disks.size(),2);auto s=disks[1].toObject().value("summary").toObject();QCOMPARE(s.value("health").toString(),"passed");QVERIFY(!s.contains("reallocated"));QVERIFY(!s.value("rescueFirst").toBool());text.replace("0E 000000000000","0E 000000000001");s=dc::parseCrystalReport(text).value("drives").toArray()[1].toObject().value("summary").toObject();QCOMPARE(s.value("health").toString(),"caution");}
 void wideCountersAndUnknown(){auto text=report()+QStringLiteral(" (02) SYNTHETIC NVME\n----------------------------\n Model : SYNTHETIC NVME\n Interface : NVM Express\n Health Status : Unknown\n06 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF Data Units Read\n");auto s=dc::parseCrystalReport(text).value("drives").toArray()[1].toObject().value("summary").toObject();QCOMPARE(s.value("health").toString(),"unknown");auto a=s.value("attributes").toArray()[0].toObject();QVERIFY(!a.contains("raw"));QCOMPARE(a.value("rawHex").toString().size(),32);auto empty=dc::parseCrystalReport("CrystalDiskInfo 9.9.2\nNo devices\n");QVERIFY(empty.value("drives").toArray().isEmpty());QVERIFY(!empty.value("deviceMetadataDetected").toBool());}
 void sevenByteAtaRawPreserved(){auto text=report();text.replace("C2 _33 _13 __0 000000000021","C2 _33 _13 __0 01000000000021");auto s=dc::parseCrystalReport(text).value("drives").toArray()[0].toObject().value("summary").toObject();QCOMPARE(s.value("attributes").toArray().size(),4);QCOMPARE(s.value("attributes").toArray()[3].toObject().value("rawHex").toString(),"01000000000021");}
 void versionAndSizeRejected(){QCOMPARE(dc::parseCrystalReport("CrystalDiskInfo 9.2.2").value("status").toString(),"error");QCOMPARE(dc::parseCrystalReport(QString(16*1024*1024+1,'x')).value("status").toString(),"error");}
 void smartctlFullTableAndWarning(){auto s=dc::summarizeSmart({{"smart_status",QJsonObject{{"passed",true}}},{"ata_smart_attributes",QJsonObject{{"table",QJsonArray{QJsonObject{{"id",197},{"name","Current_Pending_Sector"},{"value",100},{"worst",100},{"thresh",0},{"raw",QJsonObject{{"value",16},{"string","16"}}}},QJsonObject{{"id",12},{"name","Power_Cycle_Count"},{"raw",QJsonObject{{"value",3124}}}}}}}}});QCOMPARE(s.value("health").toString(),"caution");QCOMPARE(s.value("pending").toInt(),16);auto attrs=s.value("attributes").toArray();QCOMPARE(attrs.size(),2);QCOMPARE(attrs[0].toObject().value("rawHex").toString(),"000000000010");QVERIFY(s.value("rescueFirst").toBool());}
};
QTEST_GUILESS_MAIN(CrystalTests)
#include "test_crystal.moc"
